#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [ $1 = "remove" ]; then

    rm -rf /Library/MobileSubstrate/DynamicLibraries/HecateCore.* || true

    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    else
        echo -n -e "[Legizmo] Reloading daemons in 3 seconds"
        sleep 1
        echo -n -e "[Legizmo] Reloading daemons in 2 seconds"
        sleep 1;
        echo -e "[Legizmo] Reloading daemons in 1 second"
        echo -e "[Legizmo] Reloading daemons NOW..."
        sleep 1;
        ldrestart
    fi
fi
